[terminal]
# Run greetd on TTY1
vt = 1

[default_session]
# Use tuigreet as the greeter with Sway as default session
command = "tuigreet --time --remember --remember-session --asterisks --cmd 'sway --unsupported-gpu'"
user = "greeter"
